# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-DustbinAdmin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!



  # Pods for E-DustbinAdmin

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'SwiftyJSON'
 




  target 'E-DustbinAdminTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-DustbinAdminUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
